apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  #- podinfo-canary.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
  - path: podinfo-patches.yaml
    target:
      kind: HelmRelease
